Allow spamd_update_t access antivirus_unit_file_t BZ(1774092)
wrabcak/selinux-policy-contrib pull request #168
Opened 2019-11-19 15:55 UTC by zpytela

Label /usr/lib/systemd/system/amavisd.service as antivirus_unit_file_t.
Allow antivirus_systemctl(spamd_update_t).

2019-11-19 16:20 UTC, wrabcak requested changes

2019-11-19 16:20 UTC, wrabcak commented on amavis.fc
> +/usr/lib/systemd/system/amavisd.service --	gen_context(system_u:object_r:antivirus_unit_file_t,s0)
Why is this labeled as antivirus instead of amavis?

2019-12-02 11:23 UTC, zpytela commented
Ready for review.
```
f32# rpm -qa selinux\*; matchpathcon /usr/lib/systemd/system/amavisd.service; sesearch -A -s spamd_update_t -t systemd_unit_file_t -c file -p getattrselinux-policy-3.14.5-18.fc32.noarch
selinux-policy-targeted-3.14.5-18.fc32.noarch
selinux-policy-devel-3.14.5-18.fc32.noarch
/usr/lib/systemd/system/amavisd.service system_u:object_r:systemd_unit_file_t:s0
f32# rpm -F selinux-policy-*
f32# rpm -qa selinux\*; matchpathcon /usr/lib/systemd/system/amavisd.service; sesearch -A -s spamd_update_t -t antivirus_unit_file_t -c file -p getattr
selinux-policy-devel-3.14.5-18.200.bz1774092.fc32.noarch
selinux-policy-3.14.5-18.200.bz1774092.fc32.noarch
selinux-policy-targeted-3.14.5-18.200.bz1774092.fc32.noarch
/usr/lib/systemd/system/amavisd.service system_u:object_r:antivirus_unit_file_t:s0
allow spamd_update_t antivirus_unit_file_t:file { getattr ioctl lock open read };
```

2019-12-02 11:40 UTC, wrabcak requested changes

2019-12-02 11:40 UTC, wrabcak commented on antivirus.fc
> +/usr/lib/systemd/system/amavisd.service	--	gen_context(system_u:object_r:antivirus_unit_file_t,s0)
Instead of amavisd.service there could be amavisd.* to match also another possible systemd unit file types.

2019-12-02 12:02 UTC, zpytela commented
OK, changed to be alike a similar line for clamd.

2019-12-02 12:10 UTC, wrabcak approved these changes

2019-12-02 12:10 UTC, wrabcak commented
LGTM. 
Thanks.

2019-12-02 12:11 UTC, merged