rpm: Label rpmdb consistently usr_t on ostree/Atomic systems
wrabcak/selinux-policy-contrib pull request #43
Opened 2018-01-08 15:55 UTC by cgwalters

This ensures that hardlinking works.

See https://bugzilla.redhat.com/show_bug.cgi?id=1526191
https://github.com/projectatomic/rpm-ostree/pull/959#issuecomment-325780234
https://github.com/projectatomic/rpm-ostree/pull/1142

2018-01-08 15:55 UTC, cgwalters commented
Before + after:

```
$ ostree --repo=repo-build ls -C -X fedora/27/x86_64/atomic-host /usr/share/rpm/Packages /usr/lib/sysimage/rpm-ostree-base-db/Packages
-00644 0 0 21950464 9971738ce8279cbd1585cfe7058be819120d5840740585714f8a5e976d57b868 { [(b'security.selinux', b'system_u:object_r:usr_t:s0')] } /usr/share/rpm/Packages
-00644 0 0 21950464 9971738ce8279cbd1585cfe7058be819120d5840740585714f8a5e976d57b868 { [(b'security.selinux', b'system_u:object_r:usr_t:s0')] } /usr/lib/sysimage/rpm-ostree-base-db/Packages
$ ostree --repo=repo-build ls -C -X fedora/27/x86_64/atomic-host^ /usr/share/rpm/Packages /usr/lib/sysimage/rpm-ostree-base-db/Packages
-00644 0 0 21901312 fb8da9c4bc8707724097a84ba597e44ed5c6e016f28a82e49a7643c2d26ffae9 { [(b'security.selinux', b'system_u:object_r:rpm_var_lib_t:s0')] } /usr/share/rpm/Packages
-00644 0 0 21901312 a0bddda60fa3be68bcb65c02ff2a851d4926a13521ee7ca7f3182951d35e0eda { [(b'security.selinux', b'system_u:object_r:lib_t:s0')] } /usr/lib/sysimage/rpm-ostree-base-db/Packages
$
```

2018-01-11 14:49 UTC, Conan-Kudo approved these changes

2018-01-19 10:21 UTC, wrabcak requested changes
LGTM, except definition for /usr/lib/sysimage/ better place to define it in files.fc file in base repo.

2018-01-19 10:21 UTC, wrabcak commented on rpm.fc
> +/usr/share/rpm(/.*)?			gen_context(system_u:object_r:usr_t,s0)
This looks OK, should nothing break.

2018-01-19 10:21 UTC, wrabcak commented on rpm.fc
> +/usr/lib/sysimage(/.*)?			gen_context(system_u:object_r:usr_t,s0)
I prefer move this definition to https://github.com/fedora-selinux/selinux-policy/blob/rawhide/policy/modules/kernel/files.fc

2018-01-23 19:53 UTC, cgwalters commented
OK, updated :new: :arrow_up: 

See also: https://github.com/fedora-selinux/selinux-policy/pull/209

2018-01-24 12:35 UTC, merged

2018-01-24 12:35 UTC, wrabcak commented
LGTM.