Allow keepalived_t create and write a file under /tmp
wrabcak/selinux-policy-contrib pull request #47
Opened 2018-01-27 23:06 UTC by masatake

keepalived writes out its running statics to /tmp/keepalived.data when
it receives SIGUSR2. This change allows it.

Signed-off-by: Masatake YAMATO <yamato@redhat.com>

2018-01-29 15:40 UTC, wrabcak requested changes

2018-01-29 15:40 UTC, wrabcak commented on keepalived.te
> +allow keepalived_t keepalived_tmp_t:file { create_file_perms write_file_perms };
This line should be removed and used manage_files_pattern macro like on line 39.

2018-01-29 15:40 UTC, wrabcak commented on keepalived.te
> +files_tmp_filetrans(keepalived_t, keepalived_tmp_t, file)
This is OK.

2018-01-30 01:38 UTC, masatake commented
Thank you for reviewing. 

keepalived just creates and writes to /tmp/keepalived.data. It never reads the file.
It overwrites the file if it exists. ( I tested the temporary file is created well with my patch.)
`manage_file_perms` gives more permissions to `keepalived_t`. Should I use `manage_files_pattern` macro anyway?

2018-01-31 12:13 UTC, wrabcak commented
Ok then, could move allow rule from line 37 to line 69? I'll merge it. 

Thanks,
Lukas

2018-01-31 12:19 UTC, wrabcak commented
Ok then, could move allow rule from line 37 to line 69? I'll merge it. 

Thanks,
Lukas

2018-01-31 13:22 UTC, masatake commented
Updated.

2018-01-31 14:12 UTC, wrabcak commented
LGTM. 
Thanks.

2018-01-31 14:12 UTC, merged

2018-01-31 14:38 UTC, masatake commented
Thank you.