Add file transition for /var/lib/arpwatch/.esmtp_queue
wrabcak/selinux-policy-contrib pull request #77
Opened 2018-12-18 16:47 UTC by zpytela

Add file transition so that system_mail_t can in the /var/lib/arpwatch directory
with arpwatch_data_t context create .esmtp_queue directory with mail_home_rw_t context.
It is required for the arpwatch service being able to send emails.

Signed-off-by: Zdenek Pytela <zpytela@redhat.com>

2018-12-18 19:20 UTC, bachradsusi commented
```
policy/modules/contrib/arpwatch.te:94:ERROR 'unknown type mail_home_rw_t used in transition definition' at token ';' on line 2830:
	type_transition system_mail_t arpwatch_data_t:dir mail_home_rw_t ".esmtp_queue";
#line 94
```

2018-12-19 15:50 UTC, zpytela commented
3 commits merged into one and the commit message updated

2018-12-20 21:00 UTC, wrabcak requested changes
Added few comments, you're declaring type which already exits and this can be handled by new or updated existing interface.

2018-12-20 21:00 UTC, wrabcak commented on arpwatch.te
> +type mail_home_rw_t;
SELinux type mail_home_rw_t is declared here: https://github.com/fedora-selinux/selinux-policy-contrib/blob/rawhide/mta.te#L26. This should be removed.

2018-12-20 21:00 UTC, wrabcak commented on arpwatch.te
> +filetrans_pattern(system_mail_t, arpwatch_data_t, mail_home_rw_t, dir, ".esmtp_queue")
For this named_filetrans interface should be used or created if doesn't exists. For more info see:https://github.com/fedora-selinux/selinux-policy-contrib/blob/rawhide/mta.if#L1292

2019-01-14 15:58 UTC, zpytela commented
Fixed a problem with unmatching angle brackets.

2019-01-14 16:43 UTC, zpytela commented
Scratchbuild finished, selinux-policy-3.14.3-17.bz1657327.100.fc30 created.

rpm -qa selinux-policy\*;matchpathcon /var/lib/arpwatch/.esmtp_queue;sesearch -T -s system_mail_t -t arpwatch_data_t -c dir

before:
selinux-policy-devel-3.14.2-44.fc29.noarch
selinux-policy-doc-3.14.2-44.fc29.noarch
selinux-policy-3.14.2-44.fc29.noarch
selinux-policy-targeted-3.14.2-44.fc29.noarch
/var/lib/arpwatch/.esmtp_queue  system_u:object_r:arpwatch_data_t:s0

after:
selinux-policy-targeted-3.14.3-17.bz1657327.100.fc30.noarch
selinux-policy-3.14.3-17.bz1657327.100.fc30.noarch
selinux-policy-doc-3.14.3-17.bz1657327.100.fc30.noarch
selinux-policy-devel-3.14.3-17.bz1657327.100.fc30.noarch
/var/lib/arpwatch/.esmtp_queue  system_u:object_r:mail_home_rw_t:s0
type_transition system_mail_t arpwatch_data_t:dir mail_home_rw_t ".esmtp_queue";

Looks like all changes were applied. Please review again.

2019-01-14 16:53 UTC, wrabcak commented
LGTM. 

Thanks.

2019-01-14 16:53 UTC, merged